# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0002_auto_20161002_1540'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testlibrary',
            table='GlobalCodes_TestLibrary',
        ),
    ]
