# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0003_auto_20161002_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCodes_Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsectioncode', models.CharField(max_length=50)),
                ('subsection', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('halo', models.BooleanField()),
                ('wsl', models.BooleanField()),
                ('referral', models.BooleanField()),
                ('dynamics_code', models.CharField(max_length=10)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCodes_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('tfc', models.CharField(max_length=4)),
                ('loinc', models.CharField(max_length=20)),
                ('container', models.CharField(max_length=50)),
                ('result_type', models.CharField(max_length=20)),
                ('loc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referralsmanager.GlobalCodes_Locations')),
            ],
        ),
    ]
