# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0006_auto_20161003_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCodes_REFLABS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('reflab_code', models.CharField(max_length=5)),
                ('reflab_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='globalcodes_form',
            name='reflab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referralsmanager.GlobalCodes_REFLABS'),
        ),
    ]
