# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0009_auto_20161003_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCodes_LabGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
                ('published_tat', models.CharField(max_length=20)),
                ('volume_ml', models.DecimalField(decimal_places=3, max_digits=6)),
                ('frozen', models.BooleanField()),
                ('suitable_for_preanalytics', models.BooleanField()),
                ('sample_detail', models.TextField()),
                ('special_handling', models.TextField()),
                ('warnings', models.CharField(max_length=140)),
                ('assay_frequency', models.CharField(max_length=50)),
                ('method_of_sending', models.TextField()),
            ],
            options={
                'db_table': 'GlobalCodes_LabGuide',
            },
        ),
    ]
