# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0011_globalcodes_labguide_mapid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcodes_map',
            name='loinc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referralsmanager.LOINC_Main'),
        ),
    ]
