# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0015_auto_20161003_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loinc_main',
            name='CDISC_COMMON_TESTS',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='CHANGE_REASON_PUBLIC',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='DefinitionDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='EXMPL_ANSWERS',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='EXTERNAL_COPYRIGHT_NOTICE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='FORMULA',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='RELATEDNAMES2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='STATUS_TEXT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='SURVEY_QUEST_TEXT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loinc_main',
            name='UnitsAndRange',
            field=models.TextField(),
        ),
    ]
