# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0016_auto_20161003_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcodes_tlc',
            name='fixedprice',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='globalcodes_tlc',
            name='printlabel',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='globalcodes_tlc',
            name='queryflag',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='globalcodes_tlc',
            name='securitylevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globalcodes_tlc',
            name='specifiedprof',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='globalcodes_tlc',
            name='fee1',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='globalcodes_tlc',
            name='tlcname',
            field=models.CharField(max_length=25),
        ),
    ]
