# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0018_auto_20161005_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalCodes_FLAT',
            new_name='Flat',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_FORM',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_LabGuide',
            new_name='LabGuide',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_Locations',
            new_name='Locations',
        ),
        migrations.RenameModel(
            old_name='LOINC_Main',
            new_name='LOINC',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_Map',
            new_name='Map',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_REFLABS',
            new_name='Reflabs',
        ),
        migrations.RenameModel(
            old_name='GlobalCodes_TLC',
            new_name='TLC',
        ),
    ]
