# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0021_auto_20161007_1814'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set([('origin', 'tfc')]),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set([('origin', 'tfc')]),
        ),
        migrations.AlterUniqueTogether(
            name='tlc',
            unique_together=set([('origin', 'tlc')]),
        ),
    ]
