# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0024_auto_20161007_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlc',
            name='tfcs',
            field=models.ManyToManyField(through='referralsmanager.Flat', to='referralsmanager.Form'),
        ),
    ]
