# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0025_tlc_tfcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlc',
            name='tfcs',
        ),
        migrations.AlterField(
            model_name='flat',
            name='tfc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referralsmanager.Form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='tlc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referralsmanager.TLC'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set([('tlc', 'tfc')]),
        ),
    ]
