# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0028_auto_20161008_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='tfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_set', to='referralsmanager.Form'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_set', to='referralsmanager.TLC'),
        ),
    ]
