# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0029_auto_20161008_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlc',
            name='tfcs',
            field=models.ManyToManyField(through='referralsmanager.Flat', to='referralsmanager.Form'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referralsmanager.Form'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referralsmanager.TLC'),
        ),
    ]
