# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0035_auto_20161008_2305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='flat',
            name='tfc',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='tlc',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
