# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0004_globalcodes_locations_globalcodes_map'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalcodes_locations',
            table='GlobalCodes_Locations',
        ),
        migrations.AlterModelTable(
            name='globalcodes_map',
            table='GlobalCodes_Map',
        ),
    ]
