# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0012_auto_20161003_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcodes_flat',
            name='librarycode',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalcodes_flat',
            name='form',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalcodes_flat',
            name='tfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referralsmanager.GlobalCodes_FORM'),
        ),
    ]
