# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0013_auto_20161003_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalcodes_flat',
            old_name='form',
            new_name='tfc_code',
        ),
        migrations.RenameField(
            model_name='globalcodes_flat',
            old_name='librarycode',
            new_name='tlc_code',
        ),
    ]
