# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referralsmanager', '0014_auto_20161003_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalCodes_TEST',
            new_name='GlobalCodes_TLC',
        ),
        migrations.AlterModelTable(
            name='globalcodes_tlc',
            table='GlobalCodes_TLC',
        ),
    ]
