# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('tlc_code', models.CharField(max_length=4)),
                ('tfc_code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'GlobalCodes_FLAT',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('tfc', models.CharField(max_length=4)),
                ('wrksection', models.CharField(max_length=1)),
                ('testname', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=20)),
                ('functions', models.CharField(max_length=10)),
                ('reflab', models.CharField(max_length=3)),
                ('flags', models.CharField(max_length=10)),
                ('repsection', models.CharField(max_length=1)),
                ('dontwaitforme', models.CharField(max_length=1)),
                ('rownum', models.IntegerField()),
            ],
            options={
                'db_table': 'GlobalCodes_FORM',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LabGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
                ('published_tat', models.CharField(max_length=20)),
                ('volume_ml', models.DecimalField(decimal_places=3, max_digits=6)),
                ('frozen', models.BooleanField()),
                ('suitable_for_preanalytics', models.BooleanField()),
                ('sample_detail', models.TextField()),
                ('special_handling', models.TextField()),
                ('warnings', models.CharField(max_length=140)),
                ('assay_frequency', models.CharField(max_length=50)),
                ('method_of_sending', models.TextField()),
            ],
            options={
                'db_table': 'GlobalCodes_LabGuide',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsectioncode', models.CharField(max_length=50)),
                ('subsection', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('halo', models.BooleanField()),
                ('wsl', models.BooleanField()),
                ('referral', models.BooleanField()),
                ('dynamics_code', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'GlobalCodes_Locations',
            },
        ),
        migrations.CreateModel(
            name='LOINC',
            fields=[
                ('LOINC_NUM', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('COMPONENT', models.CharField(max_length=255)),
                ('PROPERTY', models.CharField(max_length=30)),
                ('TIME_ASPCT', models.CharField(max_length=15)),
                ('SYSTEM', models.CharField(max_length=100)),
                ('SCALE_TYP', models.CharField(max_length=30)),
                ('METHOD_TYP', models.CharField(max_length=50)),
                ('CLASS', models.CharField(max_length=20)),
                ('SOURCE', models.CharField(max_length=8)),
                ('VersionLastChanged', models.CharField(max_length=10)),
                ('CHNG_TYPE', models.CharField(max_length=3)),
                ('DefinitionDescription', models.TextField()),
                ('STATUS', models.CharField(max_length=11)),
                ('CONSUMER_NAME', models.CharField(max_length=255)),
                ('CLASSTYPE', models.IntegerField()),
                ('FORMULA', models.TextField()),
                ('SPECIES', models.CharField(max_length=20)),
                ('EXMPL_ANSWERS', models.TextField()),
                ('SURVEY_QUEST_TEXT', models.TextField()),
                ('SURVEY_QUEST_SRC', models.CharField(max_length=50)),
                ('UNITSREQUIRED', models.CharField(max_length=1)),
                ('SUBMITTED_UNITS', models.CharField(max_length=30)),
                ('RELATEDNAMES2', models.TextField()),
                ('SHORTNAME', models.CharField(max_length=40)),
                ('ORDER_OBS', models.CharField(max_length=15)),
                ('CDISC_COMMON_TESTS', models.TextField()),
                ('HL7_FIELD_SUBFIELD_ID', models.CharField(max_length=50)),
                ('EXTERNAL_COPYRIGHT_NOTICE', models.TextField()),
                ('EXAMPLE_UNITS', models.CharField(max_length=255)),
                ('LONG_COMMON_NAME', models.CharField(max_length=255)),
                ('UnitsAndRange', models.TextField()),
                ('DOCUMENT_SECTION', models.CharField(max_length=255)),
                ('EXAMPLE_UCUM_UNITS', models.CharField(max_length=255)),
                ('EXAMPLE_SI_UCUM_UNITS', models.CharField(max_length=255)),
                ('STATUS_REASON', models.CharField(max_length=9)),
                ('STATUS_TEXT', models.TextField()),
                ('CHANGE_REASON_PUBLIC', models.TextField()),
                ('COMMON_TEST_RANK', models.IntegerField()),
                ('COMMON_ORDER_RANK', models.IntegerField()),
                ('COMMON_SI_TEST_RANK', models.IntegerField()),
                ('HL7_ATTACHMENT_STRUCTURE', models.CharField(max_length=15)),
                ('EXTERNAL_COPYRIGHT_LINK', models.CharField(max_length=255)),
                ('PanelType', models.CharField(max_length=50)),
                ('AskAtOrderEntry', models.CharField(max_length=255)),
                ('AssociatedObservations', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'LOINC_Main',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('tfc', models.CharField(max_length=4)),
                ('container', models.CharField(max_length=50)),
                ('result_type', models.CharField(max_length=20)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Form')),
                ('loc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc1', to='app.Locations')),
                ('loc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc2', to='app.Locations')),
                ('loinc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loinc', to='app.LOINC')),
            ],
            options={
                'db_table': 'GlobalCodes_Map',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Reflabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('reflab_code', models.CharField(max_length=5)),
                ('reflab_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'GlobalCodes_REFLABS',
            },
        ),
        migrations.CreateModel(
            name='TLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('tlc', models.CharField(max_length=4)),
                ('tlctype', models.CharField(max_length=1)),
                ('fixedprice', models.CharField(max_length=1, null=True)),
                ('printlabel', models.CharField(max_length=1, null=True)),
                ('specifiedprof', models.CharField(max_length=1, null=True)),
                ('securitylevel', models.IntegerField(null=True)),
                ('queryflag', models.CharField(max_length=1, null=True)),
                ('tlcname', models.CharField(max_length=25)),
                ('fee1', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('tfcs', models.ManyToManyField(through='app.Flat', to='app.Form')),
            ],
            options={
                'db_table': 'GlobalCodes_TLC',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='app.Person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AddField(
            model_name='labguide',
            name='mapid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Map'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='app.Membership', to='app.Person'),
        ),
        migrations.AddField(
            model_name='form',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Reflabs'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Form'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TLC'),
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='app.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='tlc',
            unique_together=set([('origin', 'tlc')]),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set([('origin', 'tfc')]),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set([('origin', 'tfc')]),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set([('tlc', 'tfc')]),
        ),
    ]
